spring:
  application:
    name: agile-runner

  config:
    import: optional:file:.env[.properties]

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        model: gpt-4o-mini

  github:
    app-id: ${GITHUB_APP_ID}
    private-key: ${GITHUB_PRIVATE_KEY}